{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.secretName" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.dbPassword }}
  ConnectionStrings__DefaultConnection__Password: {{ .Values.secrets.dbPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  Jwt__Secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.adminPassword }}
  Admin__DefaultPassword: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
{{- end }}
